Algoritmo "Orientação a objetos"

tipo
CadastroCliente = registro

nome: caractere
rg: caractere
idade: inteiro

fimregistro

Var
cliente1: cadastroCliente

Inicio
escreval("Digite seu nome:")
leia(cliente1.nome)

escreval("Digite seu rg:")
leia(cliente1.rg)

escreval("Digite sua idade:")
leia(cliente1.idade)

escreval("Nome: ", cliente1.nome,"- Rg: ",cliente1.rg, "Idade: ",cliente1.idade)

Fimalgoritmo