Algoritmo "Estruturas condicionais"

Var
    nota1, nota2, nota3, media: real

Inicio
escreval("Informe a nota 1.")
     leia(nota1)
escreval("Informe a nota 2.")
     leia(nota2)
escreval("nota3")
     leia(nota3)
media <- (nota1 + nota2 + nota3)/3
    
se media < 60 entao
    escreval("Lamento, você está de recuperação.")
senao
    escreval("Você foi aprovado! Parabéns!")
fimse



Fimalgoritmo