Algoritmo "Operador escolha"

Var  voto: caractere

Inicio
   Escreval("Informe seu voto, por favor")
   leia(voto)

escolha voto
  caso "20"
       escreval("Você votou em Sakamoto.")
  caso "30"
       escreval("Você votou em Jorjana.")
  caso "40"
       escreval("Você votou em Menino Bruno.")
  caso "0"
       escreval("Nulo. Deveras superior, você votou no Reino de Deus!")

fimescolha

Fimalgoritmo