Algoritmo "Aleatório - Sorteio"

Var

  numSorteado, numSorteio : real

Inicio
   escreval("Digite seu número para o sorteio, por favor.")
  leia(numSorteio)
  aleatorio 1,10
    escreval("O número sorteado é: ")
    leia(numSorteado)
    se numSorteio = numSorteado entao
       escreval("Parabéns, você é o ganhador!")
    senao
       escreval("Que pena! Não foi dessa vez...")
    fimse
  aleatorio off

  
Fimalgoritmo
